version: 1
formatters:
  simple:
    format: '%(asctime)s %(levelname)s %(threadName)s %(module)s::%(funcName)s(%(lineno)d): %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stderr
loggers:
  mpdfront:
    level: INFO
    handlers: [console]
    propagate: no
  mpdfront.application:
    level: INFO
    handlers: [console]
    propagate: no
  mpdfront.mpd:
    level: INFO
    handlers: [console]
    propagate: no
  mpdfront.ui:
    level: INFO
    handlers: [console]
    propagate: no
root:
  level: ERROR
  handlers: [console]
